---@diagnostic disable: undefined-global
vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('', '<up>', '<nop>', { noremap = true })
vim.keymap.set('', '<down>', '<nop>', { noremap = true })
vim.keymap.set('i', '<up>', '<nop>', { noremap = true })
vim.keymap.set('i', '<down>', '<nop>', { noremap = true })
vim.keymap.set('n', '<C-down>', 'ddp', { desc = 'Move line down' })
vim.keymap.set('n', '<C-up>', 'ddkP', { desc = 'Move line up' })
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
vim.keymap.set('n', '<Leader>w', '<C-w>v', { desc = 'Vertical split' })
vim.keymap.set('n', '<C-d>', '<C-d>zz')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', '<Leader>P', '"_dP')
vim.keymap.set('x', '<Leader>p', '"_dp')
vim.keymap.set({ 'n', 'v', 'o' }, 'Q', '<Nop>')
vim.keymap.set('n', '<C-n>', '<Cmd>Neotree toggle<CR>')
vim.keymap.set('n', '<Leader>a', 'ggVG$', { desc = 'Select entire buffer' })
