return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  opts = {
    ensure_installed = {
      'python',
      'javascript',
      'typescript',
      'tsx',
      'html',
      'css',
      'c_sharp',
      'razor',
      'vue',
      'rust',
      'xml',
      'json',
      'jsonc',
      'toml',
      'yaml',
      'markdown',
      'markdown_inline',
      'bash',
      'lua',
      'vim',
      'vimdoc',
      'regex',
      'graphql',
    },
    highlight = { enable = true },
    indent = { enable = true },
    auto_install = true,
  },
}
